---
api_version: "2"
image: "centos/8"
ip_part: "192.160.0"
# node_count: 2
user: "vagrant"

cluster:
    master: "master-node"
    node: "worker-node"

resources:
    master:
        cpus: 1
        memory: 1024
    node:
        count: 2
        cpus: 2
        memory: 2048

net:
    network_type: private_network
