---
api_version: "2"
image: "bento/ubuntu-18.04"
ip_part: "192.160.0"
user: "vagrant"

cluster:
    master: "master-node"
    node: "worker-node"

resources:
    master:
        cpus: 2
        memory: 2048
    node:
        cpus: 2
        memory: 2048
        count: 2

net:
    network_type: private_network
