---
api_version: "2"
image: "bento/ubuntu-18.04"
ip_part: "10.240.0"
user: "vagrant"

cluster:
    master: "controller"
    node: "worker"

resources:
    master:
        cpus: 3
        memory: 2048
        count: 3
        ip_prefix: 10
    node:
        cpus: 2
        memory: 2048
        count: 2
        ip_prefix: 20

net:
    network_type: private_network
